# Generated by Django 4.2.10 on 2024-02-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_appointment_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
